// <auto-generated />
namespace LRTFSpeakers.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class speakernotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(speakernotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201509021333438_speakernotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
